### ISSUE TITLE
Applicable query results + config

### ISSUE THREAD

**Issue by ch-sander** [sparna-git/Sparnatural-yasgui-plugins#21]
I might have missed it but is there further documentation on how the plugins work? https://docs.sparnatural.eu/YasGUI-plugins.html is only on the tableX widget.

1. My Map widget renders WKT successfully, but how will it render GeoJSON? Is this only about the data type, e.g. a literal with a GeoJSON string of a specific data type? Or should the GeoJSON itself be in triples/RDF (via JSON-LD specs)?
2. The Stats plugin won't render my xsd:integer -- which however works for the demo of yasgui.org and https://yasgui.triply.cc/.
3. Can the `uriHrefAdapter` be defined globally for all the Plugins and/or individually per Plugin?
4. I see some commits since the 1.0.0 release -- anything one should be aware of when importing/binding the release built js file?

**Comment by tfrancart** [comment]
Hi @ch-sander 

1. only wktLiterals are supported right now. We may support cases where we have 2 columns for lat and long, but nothing is planned to support GeoJSON
2. right now the Stats plugin is a bit too restrictive and works only if the *query* uses a count. See sparnatural-yasr-plugin-stats/index.ts line 93. This is too restrictive and needs to be changed.
3. Unfortunately, no. `uriHrefAdapter` is only valid for the TableX plugin. But it should definitely go somehow global or also be available on other plugins as well. Actually, I think we could make it as a pre-processing on the result set bindings, so that it becomes available for any plugin, even not ours, and even not in YasGUI
4. Sorry, we are lacking bandwidth to do proper documentation and proper release. I am not sure I totally get your question but major enhancements have been made in the Map plugin, the Stats plugin and the Grid plugin since the release. But they have not been packaged in a release.

**Comment by ch-sander** [comment]
Clear replies! Thanks!
As for the Stats plugin: I had been using a count, bound to `object_8_count`. Do you maybe have an example query that complies with the plugin?

**Comment by tfrancart** [comment]
Make sure your Sparnatural correctly sends both the configuration and the query to the plugins. See function `bindSparnaturalWithYasrPlugins` in the file sparnatural-bings.js in the release.
Currently, the Stats plugin requires that (it probably shouldn't) :

```javascript
/**
 * Binds Sparnatural with its YasR plugins, by notifying them of
 * the configuration and of the query being executed.
 * 
 * - On sparnatural `init` event : calls notifyConfiguration(specProvider) on each Yasr plugin
 * - On sparnatural `queryUpdated` event : calls notifyQuery(queryJson) on each Yasr plugin
 **/
bindSparnaturalWithYasrPlugins = function(sparnatural, yasr) {

    sparnatural.addEventListener("init", (event) => {
      // notify the specification to yasr plugins
      for (const plugin in yasr.plugins) {
        if (yasr.plugins[plugin].notifyConfiguration) {
          yasr.plugins[plugin].notifyConfiguration(
            sparnatural.sparnatural.specProvider
          );
        }
      }
    });

    sparnatural.addEventListener("queryUpdated", (event) => {
      // notify the query to yasr plugins
      for (const plugin in yasr.plugins) {
        if (yasr.plugins[plugin].notifyQuery) {
          yasr.plugins[plugin].notifyQuery(event.detail.queryJson);
        }
      }
    });
}
```

**Comment by ch-sander** [comment]
Seems to work now! Thanks!
![grafik](https://github.com/user-attachments/assets/6088b5d7-013d-4cbc-9d7f-8907b02f9f00)

**Comment by tfrancart** [comment]
@ch-sander a release was packaged : https://github.com/sparna-git/Sparnatural-yasgui-plugins/releases/tag/2.0.1
Documentation has been improved : https://github.com/sparna-git/Sparnatural-yasgui-plugins/blob/main/README.md and https://docs.sparnatural.eu/YasGUI-plugins.html

**Comment by ch-sander** [comment]
@tfrancart wonderful, will test it!

**Comment by ch-sander** [comment]
It seems these UI tools have disappeared. How can I resurrect them?

![grafik](https://github.com/user-attachments/assets/9cd12fdc-688f-45cd-88d7-0ae0b2e80fa8)

**Comment by ch-sander** [comment]
`includeControls: true`, needed to be made explicit (I think it had been true by default before...?)
